version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: name_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: geekshubs2024
      MYSQL_DATABASE: main_database
    ports:
      - "3306:3306"
    networks:
      - my_network
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

networks:
  my_network:
